//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Инвентаризация
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventarization : DbContext
    {
        public Inventarization()
            : base("name=Inventarization")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invent_Users> Invent_Users { get; set; }
        public virtual DbSet<InventFirstRoom> InventFirstRooms { get; set; }
        public virtual DbSet<InventName> InventNames { get; set; }
        public virtual DbSet<InventSecondRoom> InventSecondRooms { get; set; }
        public virtual DbSet<InventThirdRoom> InventThirdRooms { get; set; }
    }
}
