//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Инвентаризация
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventThirdRoom
    {
        public int Id { get; set; }
        public int Name { get; set; }
        public string InventNumber { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual InventName InventName { get; set; }
    }
}
